name: CI

on: 
  push:
    tags:
    - 'v'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Creating new docker image
        uses: zenato/docker-action@master 
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: yohanson555/test-1
          tag: 1.0
